site_name: FACET Language
site_description: Deterministic markup for AI instructions
site_author: Emil Rokossovskiy
site_url: https://facet-lang.readthedocs.io/

repo_name: rokoss21/FACET
repo_url: https://github.com/rokoss21/FACET
edit_uri: edit/main/docs/

copyright: |
  &copy; 2025 Emil Rokossovskiy |
  <a href="https://github.com/rokoss21/FACET/blob/main/LICENSE">MIT License</a>

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

plugins:
  - search
  - mermaid2
  - macros
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: rokoss21/FACET
      branch: main
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: rokoss21
      repo: FACET
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
      - CLI Usage: getting-started/cli.md
  - Language Guide:
      - Overview: language/overview.md
      - Syntax: language/syntax.md
      - Data Types: language/data-types.md
      - Facets: language/facets.md
      - Lenses: language/lenses.md
      - Contracts: language/contracts.md
  - API Reference:
      - Python API: api/python.md
      - CLI Reference: api/cli.md
      - Error Codes: api/errors.md
  - Examples: examples/index.md
  - Specification:
      - Full Spec (v1.0 r1): spec/full.md
      - Short Spec (v1.0 r1): spec/short.md
  - Development:
      - Contributing: development/contributing.md
      - Architecture: development/architecture.md
      - Testing: development/testing.md
  - About:
      - Changelog: about/changelog.md
      - License: about/license.md
      - Security: about/security.md

extra:
  version:
    provider: mike
    default: latest

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rokoss21/FACET
      name: GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/facet-lang/
      name: PyPI
    - icon: fontawesome/solid/book
      link: https://facet-lang.readthedocs.io/
      name: Documentation

  generator: false

# Customization
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
